spring.application.name=PPT

spring.datasource.url=jdbc:postgresql://localhost:5432/Chat_Bot
spring.datasource.username=postgres
spring.datasource.password=080908

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true